name: Build & deploy vision-client

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container: node:slim

    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build app
        run: |
          NODE_OPTIONS='--max_old_space_size=4096' 
          npm install
          npm run build

      - name: Archive production build
        run: tar cvzf dist.tar.gz --exclude=node_modules dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist.tar.gz

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Extract archive
        run: tar xvzf dist.tar.gz

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: vision-client
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_314DAEEF5BEB4A62B847B334E0D3BCB2 }}
          package: ./dist
